### ISSUE TITLE
Image upload format

### ISSUE THREAD

**Issue by vict0rsch** [cc-ai/climatecollection#10]
Why Only *.jpeg and *.png images will be accepted?

Can't we just convert stuff on the backend ? we should make it as easy as possible for users

**Comment by notoraptor** [comment]
I guess we should set a list of allowed formats, to not allow any kind of file to be uploaded (e.g. `.exe` files, script files, or strange files).

Also, I guess backend work on converting images should be simplified, so I suggest to allow only images formats (ie. jpeg, png, and also gif, raw, webm, tiff, and an exhaustive list of known image formats) and reject any complicated format (like PDF).

**Comment by notoraptor** [comment]
Hi @vict0rsch I add a commit to accept all image format: https://github.com/cc-ai/climatecollection/commit/e1d5b1a79927cecc208e92b483554346e4994c2f .

**Comment by Vahe987** [comment]
ok, good, accepting all image formats is good enough!
@vict0rsch you can close the issue I think

**Comment by vict0rsch** [comment]
Yeah I really meant all kinds of *images* :)
