### ISSUE TITLE
Update font of "Drag and Drop files here" text

### ISSUE THREAD

**Issue by marpaia** [cc-ai/climatecollection#12]
The text where it says "Drag and Drop files here, or Click to select files" is using a serif font but the rest of the app is using a sans serif font. I don't think it's super urgent, but perhaps we could update the "Drag and Drop" text so that it's consistent with the rest of the app.

<img width="1372" alt="Screen Shot 2019-06-21 at 11 26 03 AM" src="https://user-images.githubusercontent.com/927168/59940525-2b69f100-9418-11e9-8298-6fb57c91e619.png">

**Comment by notoraptor** [comment]
Hi ! This should be fixed with the latest version of `master` branch, as I installed a font (`Public Sans`) that should be used everywhere on the site.

**Comment by marpaia** [comment]
Awesome!
