### ISSUE TITLE
enforce https

### ISSUE THREAD

**Issue by vict0rsch** [cc-ai/climatecollection#21]
serverside force https

**Comment by notoraptor** [comment]
Hi @vict0rsch ! What do you mean by "serverside force https" ?

Anyway, site is available under HTTPS too! https://climatepix.mila.quebec/


<blockquote></blockquote>

**Comment by vict0rsch** [comment]
I mean on the server, automatically redirect http requests to https

**Comment by notoraptor** [comment]
Ok! I'll look for how to do that with @marpaia !

**Comment by marpaia** [comment]
Looking into this, I was able to get this done with a slight modification to the `app.yaml` file used to deploy the site to Google App Engine. Note how force browsing http://climatepix.mila.quebec will now automatically redirect to https://climatepix.mila.quebec.

<blockquote><img src="./favicon.ico" width="48" align="right"><div><strong><a href="http://climatepix.mila.quebec/">React App</a></strong></div></blockquote>
<blockquote><img src="./favicon.ico" width="48" align="right"><div><strong><a href="https://climatepix.mila.quebec/">React App</a></strong></div></blockquote>
