### ISSUE TITLE
Overlap in images

### ISSUE THREAD

**Issue by vict0rsch** [cc-ai/climatecollection#7]
<img width="1261" alt="Capture d’écran 2019-06-19 à 00 41 45" src="https://user-images.githubusercontent.com/9283470/59724701-1c721b80-922b-11e9-8097-fc0b163f99fe.png">

**Comment by notoraptor** [comment]
Hi @vict0rsch it should be fixed now: http://ccai-upload.azurewebsites.net/

<blockquote><img src="./favicon.ico" width="48" align="right"><div><strong><a href="http://ccai-upload.azurewebsites.net/">React App</a></strong></div></blockquote>
