### ISSUE TITLE
Change upload typo

### ISSUE THREAD

**Issue by vict0rsch** [cc-ai/climatecollection#8]
just a reminder :p

**Comment by notoraptor** [comment]
Which typo should I use ?

**Comment by sashavor** [comment]
Typo means mistake in the text

**Comment by notoraptor** [comment]
Oh, ok ! Sorry ! I don't yet see some mistakes, so I will wait for @vict0rsch suggestions !

**Comment by Vahe987** [comment]
I didn't find any typos either, closing this issue, if you have one, create a new issue with a specifications so we can see. thank you

**Comment by vict0rsch** [comment]
@notoraptor was right guys I was talking about typography, font-family to be precise

**Comment by Vahe987** [comment]
haha, ok, so what is wrong with a typography, what we should use in your opinion?

**Comment by vict0rsch** [comment]
You can use any typo, just it's not consistent across the website as is.

Fonts I like are [Public Sans](https://github.com/uswds/public-sans) and [Inria Sans ](https://github.com/BlackFoundry/InriaFonts)

**Comment by vict0rsch** [comment]
(still looking for open sans reference, I might be mistaken in the name)

**Comment by vict0rsch** [comment]
I just meant to open the issue as a note for later that at some point we want to think about fonts and that this is not ready for production: 
<img width="517" alt="Capture d’écran 2019-06-20 à 15 57 06" src="https://user-images.githubusercontent.com/9283470/59854938-2c494700-9374-11e9-9841-5779e73f233d.png">

**Comment by Vahe987** [comment]
oh, you mean to have same font everywhere? I agree. Will ask to Alice tomorrow

**Comment by vict0rsch** [comment]
yeah, and the font I meant was Public Sans, updated my comment

**Comment by Vahe987** [comment]
@notoraptor can you please change the font to Public Sans to see and to show Alice tomorrow?

**Comment by notoraptor** [comment]
Hi, here ! I updated the master branch with a commit that adds and uses Public Sans font everywhere on the site. You can see it here: http://ccai-upload.azurewebsites.net/


<blockquote><img src="./favicon.ico" width="48" align="right"><div><strong><a href="http://ccai-upload.azurewebsites.net/">React App</a></strong></div></blockquote>

**Comment by Vahe987** [comment]
good job
